version = 0.1

[testing]
[testing.global]
[testing.global.parameters]
stack_name = "uni-prop-dev-contracts"
s3_prefix = "uni-prop-dev-contracts"
s3_bucket = "aws-sam-cli-managed-dev-pipeline-r-artifactsbucket-b4bde9ggoit3"
region = "us-east-1"

[testing.deploy]
[testing.deploy.parameters]
template = "packaged-testing.yaml"
fail_on_empty_changeset = false
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=dev"

# ############################################## #

[prod]
[prod.global]
[prod.global.parameters]
stack_name = "uni-prop-prod-contracts"
s3_prefix = "uni-prop-prod-contracts"
s3_bucket = "aws-sam-cli-managed-prod-pipeline--artifactsbucket-u7y7j1f2fmwv"
region = "us-east-1"

[prod.deploy]
[prod.deploy.parameters]
template = "packaged-prod.yaml"
fail_on_empty_changeset = false
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"prod\""

# ############################################## #

[pipeline]
[pipeline.deploy]
[pipeline.deploy.parameters]
stack_name = "uni-prop-contracts-pipeline"
s3_prefix = "uni-prop-contracts-pipeline"
resolve_s3 = true
fail_on_empty_changeset = false
template = "codepipeline.yaml"
capabilities = "CAPABILITY_IAM"