# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
AWSTemplateFormatVersion: "2010-09-09"
Description: Event Schemas for use by the Properties Service

Parameters:
  Stage:
    Type: String
    Default: local
    AllowedValues:
      - local
      - dev
      - prod

Resources:
  EventRegistry:
    Type: AWS::EventSchemas::Registry
    Properties: 
      Description: 'Event schemas for Unicorn Properties'
      RegistryName:
        Fn::Sub: "{{resolve:ssm:/uni-prop/UnicornPropertiesNamespace}}-${Stage}"

  EventRegistryPolicy:
    Type: AWS::EventSchemas::RegistryPolicy
    Properties: 
      RegistryName:
        Fn::GetAtt: EventRegistry.RegistryName
      Policy:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowExternalServices
            Effect: Allow
            Principal:
              AWS:
                - Ref: AWS::AccountId
            Action:
              - schemas:DescribeCodeBinding
              - schemas:DescribeRegistry
              - schemas:DescribeSchema
              - schemas:GetCodeBindingSource
              - schemas:ListSchemas
              - schemas:ListSchemaVersions
              - schemas:SearchSchemas
            Resource:
              - Fn::GetAtt: EventRegistry.RegistryArn
              - Fn::Sub: "arn:${AWS::Partition}:schemas:${AWS::Region}:${AWS::AccountId}:schema/${EventRegistry.RegistryName}*"

  PublicationEvaluationCompleted:
     Type: AWS::EventSchemas::Schema
     Properties:
       Type: 'OpenApi3'
       RegistryName:
         Fn::GetAtt: EventRegistry.RegistryName
       SchemaName:
         Fn::Sub: '{{resolve:ssm:/uni-prop/UnicornPropertiesNamespace}}@PublicationEvaluationCompleted'
       Description: 'The schema for when a property evaluation is completed'
       Content:
         Fn::Sub: |
           {
                   "openapi": "3.0.0",
                   "info": {
                     "version": "1.0.0",
                     "title": "PublicationEvaluationCompleted"
                   },
                   "paths": {},
                   "components": {
                     "schemas": {
                       "PublicationEvaluationCompleted": {
                         "type": "object",
                         "properties": {
                           "property_id": {
                             "type": "string",
                             "description": "Unique identifier for the property (e.g., country/city/street/number)"
                           },
                           "evaluation_result": {
                             "type": "string",
                             "description": "Result of the evaluation (e.g., APPROVED, REJECTED)",
                             "enum": ["APPROVED", "REJECTED"]
                           }
                         },
                         "required": ["property_id", "evaluation_result"],
                         "additionalProperties": false
                       }
                     }
                   }
                 }