version = 0.1

[default.global.parameters]
stack_name = "uni-prop-local-contracts"
s3_prefix = "uni-prop-local-contracts"
resolve_s3 = true
resolve_image_repositories = true

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
disable_rollback = true
confirm_changeset = true
fail_on_empty_changeset = false
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "Stage=\"local\""
region = "us-east-1"
image_repositories = []

[default.validate.parameters]
lint = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"