name: Deploy SAM Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python (for SAM CLI)
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'  # or whatever version SAM CLI supports

    - name: Install AWS SAM CLI
      run: |
        pip install aws-sam-cli

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Change to your region

    - name: Run Tests
      run: |
        echo "Running tests..."
        npm install
        npm test

    - name: Build SAM Application
      run: |
        sam build

    - name: Deploy SAM Application
      run: |
        sam deploy \
          --stack-name my-app-stack \
          --s3-bucket my-sam-deployments-bucket \
          --capabilities CAPABILITY_IAM \
          --parameter-overrides \
            Environment=prod \
            AppName=my-app \
          --no-confirm-changeset \
          --no-fail-on-empty-changeset
